baseURL = "https://www.drawbuildplay.com/"
languageCode = "en-us"
title = "DrawBuildPlay"
theme = "massively"
disqusShortname = "hugo-massively"
googleAnalytics = "UA-73309318-1"

# set below parameter to define a favicon
[params]
    favicon = "/favicon.png"
    author = "Amit Gandhi"
	site_description = "Useful tips and tricks for designing and building things yourself"
	description = "Useful tips and tricks for designing and building things yourself"

[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML", "AMP"]

# Below parameters can be set to override default post settings
[params.posts]
     foldername = "blog"
     pagesize = "10"
     featuredpost = "false"

[permalinks]
  blog = "/blog/:title/"

[taxonomies]
  category = "categories"

[languages]
[languages.en]
  languageName = "English"

